#!/bin/bash
#SBATCH --job-name=genomabed
#SBATCH --output=genomabedtools70.txt
#SBATCH --ntasks=1
#SBATCH --time=70:00:00
#SBATCH --partition=nu

module load gcc/11.1.0
module load bedtools/2.27.1

bedtools getfasta -fi a.chroococcum.fna -bed genomamayor70.bed
